name: CI

on: [push, pull_request]

jobs:
  python:
    name: Python Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build and Test
      run: |
        pip install multidict
        pip install gql
        pip install requests
        pip install regex
        pip install PyGithub
        pip install requests_toolbelt
        pip install coverage
        cd grrs/src/test
        python3 -m unittest discover -v
  rust:
    name: Rust Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build and Test
      run: |
        cd grrs
        cargo clean
        cargo build
        cargo test --verbose
