name: CI

on: [push, pull_request]

jobs:
  python:
    name: Python Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        packages: |
          numpy==latest
          pandas==latest
          gql==latest
          requests==latest
          regex==latest
          PyGithub==latest
          requests_toolbelt==latest
          coverage==latest
    - name: Build and Test
      run: |
        cd grrs/src/test
        python3 -m coverage run -m unittest
  rust:
    name: Rust Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build and Test
      run: |
        cd grrs
        cargo clean
        cargo build
        cargo test --verbose
